"""
MCP Tools package - Integration tools for GitHub, Jira, and Google Drive
"""

from .base import get_access_token, load_db_config, DB_CONFIG
from .integration_tools import (
    # GitHub Tools
    github_list_repos,
    github_search_code,
    github_read_file,
    github_list_branches,
    github_create_issue,
    github_list_issues,
    github_get_issue,
    github_list_prs,
    github_get_pr,
    github_create_pr,
    github_create_file,
    github_update_file,
    github_merge_pr,
    github_create_branch,
    github_list_commits,
    github_get_repo,
    github_list_collaborators,
    # Jira Tools
    jira_list_projects,
    jira_search_issues,
    jira_get_issue,
    jira_get_project_details,
    jira_get_project_analytics,
    jira_get_issue_comments,
    jira_get_all_projects_summary,
    jira_list_filters,
    jira_execute_filter,
    jira_create_issue,
    jira_update_issue,
    jira_add_comment,
    jira_transition_issue,
    jira_list_boards,
    jira_list_sprints,
    jira_add_attachment,
    jira_log_work,
    jira_list_my_active_projects,
    jira_list_projects_with_role,
    # Google Drive Tools
    drive_list_files,
    drive_read_file,
    drive_search_files,
    drive_list_shared_files,
    drive_list_folder_contents,
    drive_create_file,
    drive_update_file,
    drive_create_folder,
    drive_share_file,
    drive_delete_file,
    drive_export_file,
)

__all__ = [
    'get_access_token',
    'load_db_config',
    'DB_CONFIG',
    # GitHub
    'github_list_repos',
    'github_search_code',
    'github_read_file',
    'github_list_branches',
    'github_create_issue',
    'github_list_issues',
    'github_get_issue',
    'github_list_prs',
    'github_get_pr',
    'github_create_pr',
    'github_create_file',
    'github_update_file',
    'github_merge_pr',
    'github_create_branch',
    'github_list_commits',
    'github_get_repo',
    'github_list_collaborators',
    # Jira
    'jira_list_projects',
    'jira_search_issues',
    'jira_get_issue',
    'jira_get_project_details',
    'jira_get_project_analytics',
    'jira_get_issue_comments',
    'jira_get_all_projects_summary',
    'jira_list_filters',
    'jira_execute_filter',
    'jira_create_issue',
    'jira_update_issue',
    'jira_add_comment',
    'jira_transition_issue',
    'jira_list_boards',
    'jira_list_sprints',
    'jira_add_attachment',
    'jira_log_work',
    'jira_list_my_active_projects',
    'jira_list_projects_with_role',
    # Drive
    'drive_list_files',
    'drive_read_file',
    'drive_search_files',
    'drive_list_shared_files',
    'drive_list_folder_contents',
    'drive_create_file',
    'drive_update_file',
    'drive_create_folder',
    'drive_share_file',
    'drive_delete_file',
    'drive_export_file',
]

